### ISSUE TITLE
Feedback for code changing - see section 4.1

### ISSUE THREAD

**Issue by Amberrizvi** [Amberrizvi/41189-assignment-template#2]
@juancastilla 
Section 4.1 details my entire question. Below **in bold** is what I think we can begin to change about the code, but I haven't got very far as I am unsure of what i can change to represent what I want to:

to setup
  clear-all
  set-default-shape industry "circle"
  ;; make the initial network of **three** industries and an edge
  make-node nobody        ;; first node, unattached
  make-node industry 0      ;; second node, attached to first node
  **make-node industry 1**
  reset-ticks
end

**Comment by juancastilla** [comment]
@Amberrizvi 
This is Netlogo code, it won't run in Jupyter. Please see my feedback in the other issue...there is lots of Python code out there that you can use. The NetworkX library provides all the functionality that you need. The barabasi_albert_graph function in NetworkX can generate preferential attachment models for you in one line of code. I left a few links for you to check out ;)
